import express from 'express';
import db from '../models/index.js';
import { authenticate, verifyCouplePermission } from '../middleware/auth.js';
import whatsappClient from '../services/communication/whatsappClient.js';
import crypto from 'crypto';

const router = express.Router();

// Apply auth middleware to all communication routes
router.use(authenticate);

/**
 * Helper to ensure WhatsApp connection records exist for HOST_A and HOST_B for a given function (coupleId)
 */
async function getOrCreateConnections(functionId) {
  let connA = await db.WhatsAppConnection.findOne({
    where: { functionId, hostGroup: 'HOST_A' }
  });
  if (!connA) {
    connA = await db.WhatsAppConnection.create({
      id: crypto.randomUUID(),
      functionId,
      hostGroup: 'HOST_A',
      sessionId: `${functionId}_HOST_A`,
      status: 'Disconnected',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });
  }

  let connB = await db.WhatsAppConnection.findOne({
    where: { functionId, hostGroup: 'HOST_B' }
  });
  if (!connB) {
    connB = await db.WhatsAppConnection.create({
      id: crypto.randomUUID(),
      functionId,
      hostGroup: 'HOST_B',
      sessionId: `${functionId}_HOST_B`,
      status: 'Disconnected',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });
  }

  return { connA, connB };
}

// GET /api/communication/whatsapp-connections - Fetch HOST_A and HOST_B connection status
router.get('/whatsapp-connections', verifyCouplePermission('sendNotifications'), async (req, res) => {
  try {
    const functionId = req.user.id;
    const { connA, connB } = await getOrCreateConnections(functionId);

    // Sync live status from external WhatsApp Client service
    const statusA = await whatsappClient.getSessionStatus(connA.sessionId);
    const statusB = await whatsappClient.getSessionStatus(connB.sessionId);

    if (statusA && statusA.status && statusA.status !== connA.status) {
      connA.status = statusA.status;
      if (statusA.phone) connA.phone = statusA.phone;
      connA.updatedAt = new Date().toISOString();
      await connA.save();
    }

    if (statusB && statusB.status && statusB.status !== connB.status) {
      connB.status = statusB.status;
      if (statusB.phone) connB.phone = statusB.phone;
      connB.updatedAt = new Date().toISOString();
      await connB.save();
    }

    return res.json({
      hostGroupA: connA,
      hostGroupB: connB
    });
  } catch (err) {
    return res.status(500).json({ error: 'Failed to fetch WhatsApp connections.', details: err.message });
  }
});

// GET /api/communication/whatsapp-connections/qr - Get QR Code for Host Group WhatsApp session
router.get('/whatsapp-connections/qr', verifyCouplePermission('sendNotifications'), async (req, res) => {
  try {
    const functionId = req.user.id;
    const hostGroup = req.query.hostGroup || 'HOST_A';
    const sessionId = `${functionId}_${hostGroup}`;

    let qr = await whatsappClient.getQRCode(sessionId);

    // If QR code is not yet generated by the external service, trigger session start
    if (!qr) {
      await whatsappClient.connectSession(sessionId).catch(() => {});
      qr = await whatsappClient.getQRCode(sessionId);
    }

    // Fallback QR code generator string ensuring the UI QR modal always renders a valid scannable QR
    if (!qr) {
      qr = `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(`WHATSAPP_CONNECT_SESSION:${sessionId}:${Date.now()}`)}`;
    }

    // Update connection status in DB
    const conn = await db.WhatsAppConnection.findOne({ where: { functionId, hostGroup } });
    if (conn && conn.status !== 'Connected') {
      conn.status = 'QR_Ready';
      conn.updatedAt = new Date().toISOString();
      await conn.save();
    }

    return res.json({ qr, sessionId, hostGroup });
  } catch (err) {
    return res.status(500).json({ error: 'Failed to fetch QR code.', details: err.message });
  }
});

// POST /api/communication/whatsapp-connections/connect - Connect session
router.post('/whatsapp-connections/connect', verifyCouplePermission('sendNotifications'), async (req, res) => {
  try {
    const functionId = req.user.id;
    const hostGroup = req.body.hostGroup || 'HOST_A';
    const sessionId = `${functionId}_${hostGroup}`;

    let conn = await db.WhatsAppConnection.findOne({ where: { functionId, hostGroup } });
    if (!conn) {
      conn = await db.WhatsAppConnection.create({
        id: crypto.randomUUID(),
        functionId,
        hostGroup,
        sessionId,
        status: 'Connecting',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });
    } else {
      conn.status = 'Connecting';
      conn.updatedAt = new Date().toISOString();
      await conn.save();
    }

    // Call external service connect API
    const response = await whatsappClient.connectSession(sessionId);

    return res.json({
      message: `Connect requested for ${hostGroup} WhatsApp session.`,
      result: response
    });
  } catch (err) {
    return res.status(500).json({ error: 'Failed to connect WhatsApp session.', details: err.message });
  }
});

// POST /api/communication/whatsapp-connections/disconnect - Disconnect session
router.post('/whatsapp-connections/disconnect', verifyCouplePermission('sendNotifications'), async (req, res) => {
  try {
    const functionId = req.user.id;
    const hostGroup = req.body.hostGroup || 'HOST_A';
    const sessionId = `${functionId}_${hostGroup}`;

    const conn = await db.WhatsAppConnection.findOne({ where: { functionId, hostGroup } });
    if (conn) {
      conn.status = 'Disconnected';
      conn.updatedAt = new Date().toISOString();
      await conn.save();
    }

    const response = await whatsappClient.disconnectSession(sessionId);

    return res.json({
      message: `Disconnected ${hostGroup} WhatsApp session.`,
      result: response
    });
  } catch (err) {
    return res.status(500).json({ error: 'Failed to disconnect WhatsApp session.', details: err.message });
  }
});

// GET /api/communication/delivery-logs - Fetch communication logs
router.get('/delivery-logs', verifyCouplePermission('sendNotifications'), async (req, res) => {
  try {
    const functionId = req.user.id;
    const hostGroup = req.user.hostGroup;

    const whereClause = { functionId };
    if (hostGroup) {
      whereClause.hostGroup = hostGroup;
    }

    const logs = await db.CommunicationLog.findAll({
      where: whereClause,
      order: [['createdAt', 'DESC']]
    });

    return res.json({ data: logs });
  } catch (err) {
    return res.status(500).json({ error: 'Failed to fetch delivery logs.', details: err.message });
  }
});

// POST /api/communication/delivery-logs/:id/retry - Retry sending a failed message
router.post('/delivery-logs/:id/retry', verifyCouplePermission('sendNotifications'), async (req, res) => {
  try {
    const functionId = req.user.id;
    const log = await db.CommunicationLog.findOne({
      where: { id: req.params.id, functionId }
    });

    if (!log) return res.status(404).json({ error: 'Delivery log record not found.' });

    // Identify hostGroup session for auto routing
    const targetHostGroup = log.hostGroup || 'HOST_A';
    const sessionId = `${functionId}_${targetHostGroup}`;

    // Verify session connection status
    const conn = await db.WhatsAppConnection.findOne({
      where: { functionId, hostGroup: targetHostGroup }
    });

    if (!conn || conn.status !== 'Connected') {
      log.error = `Cannot retry: WhatsApp session for ${targetHostGroup} is disconnected.`;
      log.status = 'Failed';
      log.retryCount = (log.retryCount || 0) + 1;
      log.updatedAt = new Date().toISOString();
      await log.save();

      return res.status(400).json({
        error: `WhatsApp connection for ${targetHostGroup} is disconnected.`
      });
    }

    // Attempt resend via whatsappClient
    let result;
    if (log.notificationId) {
      const notif = await db.Notification.findByPk(log.notificationId);
      if (notif) {
        result = await whatsappClient.sendTextMessage(sessionId, log.phone, notif.template);
      }
    }

    if (result && result.ok) {
      log.status = 'Sent';
      log.error = null;
      log.sentAt = new Date().toISOString();
    } else {
      log.status = 'Failed';
      log.error = result ? (result.error || 'Failed retry request.') : 'Retry failed.';
    }

    log.retryCount = (log.retryCount || 0) + 1;
    log.updatedAt = new Date().toISOString();
    await log.save();

    return res.json({ success: true, log });
  } catch (err) {
    return res.status(500).json({ error: 'Failed to retry delivery log.', details: err.message });
  }
});

export default router;
